### YamlMime:ManagedReference
items:
- uid: System.Drawing.Printing.QueryPageSettingsEventHandler
  id: QueryPageSettingsEventHandler
  langs:
  - csharp
  name: QueryPageSettingsEventHandler
  nameWithType: QueryPageSettingsEventHandler
  fullName: System.Drawing.Printing.QueryPageSettingsEventHandler
  type: Delegate
  summary: Represents the method that handles the <xref href="System.Drawing.Printing.PrintDocument.QueryPageSettings"></xref> event of a <xref href="System.Drawing.Printing.PrintDocument"></xref>.
  remarks: "When you create a QueryPageSettingsEventHandler delegate, you identify the method that will handle the event. To associate the event with your event handler, add an instance of the delegate to the event. The event handler is called whenever the event occurs, unless you remove the delegate. For more information about event-handler delegates, see [Events](~/add/includes/ajax-current-ext-md.md).  \n  \n For more information on printing, see the <xref:System.Drawing.Printing> namespace overview."
  syntax:
    content: public delegate void QueryPageSettingsEventHandler(object sender, QueryPageSettingsEventArgs e);
  inheritance:
  - System.Delegate
  platform:
  - net462
references:
- uid: System.Delegate
  isExternal: false
  name: System.Delegate
