### YamlMime:ManagedReference
items:
- uid: System.EnterpriseServices.CompensatingResourceManager.ApplicationCrmEnabledAttribute
  id: ApplicationCrmEnabledAttribute
  children:
  - System.EnterpriseServices.CompensatingResourceManager.ApplicationCrmEnabledAttribute.#ctor
  - System.EnterpriseServices.CompensatingResourceManager.ApplicationCrmEnabledAttribute.#ctor(System.Boolean)
  - System.EnterpriseServices.CompensatingResourceManager.ApplicationCrmEnabledAttribute.Value
  langs:
  - csharp
  name: ApplicationCrmEnabledAttribute
  nameWithType: ApplicationCrmEnabledAttribute
  fullName: System.EnterpriseServices.CompensatingResourceManager.ApplicationCrmEnabledAttribute
  type: Class
  summary: Enables Compensating Resource Manger (CRM) on the tagged application.
  remarks: ''
  example:
  - "The following code example demonstrates the use of this attribute.  \n  \n [!code-vb[EnterpriseServices_Crm#3](~/add/codesnippet/visualbasic/7f097ad4-8e78-4a01-838d-_1.vb)]\n [!code-cpp[EnterpriseServices_Crm#3](~/add/codesnippet/cpp/7f097ad4-8e78-4a01-838d-_1.cpp)]\n [!code-cs[EnterpriseServices_Crm#3](~/add/codesnippet/csharp/7f097ad4-8e78-4a01-838d-_1.cs)]"
  syntax:
    content: >-
      [System.AttributeUsage(System.AttributeTargets.Assembly, Inherited=true)]

      [System.Runtime.InteropServices.ComVisible(false)]

      [System.Runtime.InteropServices.ProgId("System.EnterpriseServices.Crm.ApplicationCrmEnabledAttribute")]

      public sealed class ApplicationCrmEnabledAttribute : Attribute
  inheritance:
  - System.Attribute
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.EnterpriseServices.CompensatingResourceManager.ApplicationCrmEnabledAttribute.#ctor
  id: '#ctor'
  parent: System.EnterpriseServices.CompensatingResourceManager.ApplicationCrmEnabledAttribute
  langs:
  - csharp
  name: ApplicationCrmEnabledAttribute()
  nameWithType: ApplicationCrmEnabledAttribute.ApplicationCrmEnabledAttribute()
  fullName: System.EnterpriseServices.CompensatingResourceManager.ApplicationCrmEnabledAttribute.ApplicationCrmEnabledAttribute()
  type: Constructor
  assemblies:
  - System.EnterpriseServices
  namespace: System.EnterpriseServices.CompensatingResourceManager
  summary: Initializes a new instance of the <xref href="System.EnterpriseServices.CompensatingResourceManager.ApplicationCrmEnabledAttribute"></xref> class, setting the <xref:System.EnterpriseServices.CompensatingResourceManager.ApplicationCrmEnabledAttribute.Value*> property to <xref uid="langword_csharp_true" name="true" href=""></xref>.
  syntax:
    content: public ApplicationCrmEnabledAttribute ();
    parameters: []
  overload: System.EnterpriseServices.CompensatingResourceManager.ApplicationCrmEnabledAttribute.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.EnterpriseServices.CompensatingResourceManager.ApplicationCrmEnabledAttribute.#ctor(System.Boolean)
  id: '#ctor(System.Boolean)'
  parent: System.EnterpriseServices.CompensatingResourceManager.ApplicationCrmEnabledAttribute
  langs:
  - csharp
  name: ApplicationCrmEnabledAttribute(Boolean)
  nameWithType: ApplicationCrmEnabledAttribute.ApplicationCrmEnabledAttribute(Boolean)
  fullName: System.EnterpriseServices.CompensatingResourceManager.ApplicationCrmEnabledAttribute.ApplicationCrmEnabledAttribute(Boolean)
  type: Constructor
  assemblies:
  - System.EnterpriseServices
  namespace: System.EnterpriseServices.CompensatingResourceManager
  summary: Initializes a new instance of the <xref href="System.EnterpriseServices.CompensatingResourceManager.ApplicationCrmEnabledAttribute"></xref> class, optionally setting the <xref:System.EnterpriseServices.CompensatingResourceManager.ApplicationCrmEnabledAttribute.Value*> property to <xref uid="langword_csharp_false" name="false" href=""></xref>.
  syntax:
    content: public ApplicationCrmEnabledAttribute (bool val);
    parameters:
    - id: val
      type: System.Boolean
      description: <xref uid="langword_csharp_true" name="true" href=""></xref> to enable Compensating Resource Manager (CRM); otherwise, <xref uid="langword_csharp_false" name="false" href=""></xref>.
  overload: System.EnterpriseServices.CompensatingResourceManager.ApplicationCrmEnabledAttribute.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.EnterpriseServices.CompensatingResourceManager.ApplicationCrmEnabledAttribute.Value
  id: Value
  parent: System.EnterpriseServices.CompensatingResourceManager.ApplicationCrmEnabledAttribute
  langs:
  - csharp
  name: Value
  nameWithType: ApplicationCrmEnabledAttribute.Value
  fullName: System.EnterpriseServices.CompensatingResourceManager.ApplicationCrmEnabledAttribute.Value
  type: Property
  assemblies:
  - System.EnterpriseServices
  namespace: System.EnterpriseServices.CompensatingResourceManager
  summary: Enables or disables Compensating Resource Manager (CRM) on the tagged application.
  syntax:
    content: public bool Value { get; }
    return:
      type: System.Boolean
      description: <xref uid="langword_csharp_true" name="true" href=""></xref> if CRM is enabled; otherwise, <xref uid="langword_csharp_false" name="false" href=""></xref>. The default is <xref uid="langword_csharp_true" name="true" href=""></xref>.
  overload: System.EnterpriseServices.CompensatingResourceManager.ApplicationCrmEnabledAttribute.Value*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Attribute
  isExternal: false
  name: System.Attribute
- uid: System.EnterpriseServices.CompensatingResourceManager.ApplicationCrmEnabledAttribute.#ctor
  parent: System.EnterpriseServices.CompensatingResourceManager.ApplicationCrmEnabledAttribute
  isExternal: false
  name: ApplicationCrmEnabledAttribute()
  nameWithType: ApplicationCrmEnabledAttribute.ApplicationCrmEnabledAttribute()
  fullName: System.EnterpriseServices.CompensatingResourceManager.ApplicationCrmEnabledAttribute.ApplicationCrmEnabledAttribute()
- uid: System.EnterpriseServices.CompensatingResourceManager.ApplicationCrmEnabledAttribute.#ctor(System.Boolean)
  parent: System.EnterpriseServices.CompensatingResourceManager.ApplicationCrmEnabledAttribute
  isExternal: false
  name: ApplicationCrmEnabledAttribute(Boolean)
  nameWithType: ApplicationCrmEnabledAttribute.ApplicationCrmEnabledAttribute(Boolean)
  fullName: System.EnterpriseServices.CompensatingResourceManager.ApplicationCrmEnabledAttribute.ApplicationCrmEnabledAttribute(Boolean)
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.EnterpriseServices.CompensatingResourceManager.ApplicationCrmEnabledAttribute.Value
  parent: System.EnterpriseServices.CompensatingResourceManager.ApplicationCrmEnabledAttribute
  isExternal: false
  name: Value
  nameWithType: ApplicationCrmEnabledAttribute.Value
  fullName: System.EnterpriseServices.CompensatingResourceManager.ApplicationCrmEnabledAttribute.Value
- uid: System.EnterpriseServices.CompensatingResourceManager.ApplicationCrmEnabledAttribute.#ctor*
  parent: System.EnterpriseServices.CompensatingResourceManager.ApplicationCrmEnabledAttribute
  isExternal: false
  name: ApplicationCrmEnabledAttribute
  nameWithType: ApplicationCrmEnabledAttribute.ApplicationCrmEnabledAttribute
- uid: System.EnterpriseServices.CompensatingResourceManager.ApplicationCrmEnabledAttribute.Value*
  parent: System.EnterpriseServices.CompensatingResourceManager.ApplicationCrmEnabledAttribute
  isExternal: false
  name: Value
  nameWithType: ApplicationCrmEnabledAttribute.Value
