### YamlMime:ManagedReference
items:
- uid: System.Net.PeerToPeer.Collaboration.ApplicationChangedEventArgs
  id: ApplicationChangedEventArgs
  children:
  - System.Net.PeerToPeer.Collaboration.ApplicationChangedEventArgs.PeerApplication
  - System.Net.PeerToPeer.Collaboration.ApplicationChangedEventArgs.PeerChangeType
  - System.Net.PeerToPeer.Collaboration.ApplicationChangedEventArgs.PeerContact
  - System.Net.PeerToPeer.Collaboration.ApplicationChangedEventArgs.PeerEndPoint
  langs:
  - csharp
  name: ApplicationChangedEventArgs
  nameWithType: ApplicationChangedEventArgs
  fullName: System.Net.PeerToPeer.Collaboration.ApplicationChangedEventArgs
  type: Class
  summary: Provides qualifying information to a callback method when a <xref href="System.Net.PeerToPeer.Collaboration.PeerApplication.ApplicationChanged"></xref> event occurs.
  remarks: "An <xref:System.Net.PeerToPeer.Collaboration.ContactManager.ApplicationChanged> event is raised when:  \n  \n-   A peer starts an application within a collaboration  \n  \n-   A peer ends an application within a collaboration  \n  \n-   The <xref:System.Net.PeerToPeer.Collaboration.PeerContact> object that represents a collaborating peer has a change in its properties, such as the associated Nickname  \n  \n-   The scope of the application is changed on that peer contact's computer  \n  \n-   A peer moves to a different IP address on the network  \n  \n-  \n  \n Every class that uses the ApplicationChangedEventArgs class requires a <xref:System.Security.Permissions.PermissionState> of Unrestricted. This state is created when the <xref:System.Net.PeerToPeer.Collaboration.PeerCollaboration> object is constructed."
  syntax:
    content: 'public class ApplicationChangedEventArgs : EventArgs'
  inheritance:
  - System.EventArgs
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Net.PeerToPeer.Collaboration.ApplicationChangedEventArgs.PeerApplication
  id: PeerApplication
  parent: System.Net.PeerToPeer.Collaboration.ApplicationChangedEventArgs
  langs:
  - csharp
  name: PeerApplication
  nameWithType: ApplicationChangedEventArgs.PeerApplication
  fullName: System.Net.PeerToPeer.Collaboration.ApplicationChangedEventArgs.PeerApplication
  type: Property
  assemblies:
  - System.Net
  namespace: System.Net.PeerToPeer.Collaboration
  summary: Gets the <xref href="System.Net.PeerToPeer.Collaboration.PeerApplication"></xref> for which the event was raised.
  remarks: Unless specified, the default value for this property is `null`.
  syntax:
    content: public System.Net.PeerToPeer.Collaboration.PeerApplication PeerApplication { get; }
    return:
      type: System.Net.PeerToPeer.Collaboration.PeerApplication
      description: The <xref href="System.Net.PeerToPeer.Collaboration.PeerApplication"></xref> instance that was updated.
  overload: System.Net.PeerToPeer.Collaboration.ApplicationChangedEventArgs.PeerApplication*
  exceptions: []
  platform:
  - net462
- uid: System.Net.PeerToPeer.Collaboration.ApplicationChangedEventArgs.PeerChangeType
  id: PeerChangeType
  parent: System.Net.PeerToPeer.Collaboration.ApplicationChangedEventArgs
  langs:
  - csharp
  name: PeerChangeType
  nameWithType: ApplicationChangedEventArgs.PeerChangeType
  fullName: System.Net.PeerToPeer.Collaboration.ApplicationChangedEventArgs.PeerChangeType
  type: Property
  assemblies:
  - System.Net
  namespace: System.Net.PeerToPeer.Collaboration
  summary: Gets the type of change to the <xref href="System.Net.PeerToPeer.Collaboration.PeerApplication"></xref> that occurred.
  remarks: Unless specified, the default value for this property is `null`.
  syntax:
    content: public System.Net.PeerToPeer.Collaboration.PeerChangeType PeerChangeType { get; }
    return:
      type: System.Net.PeerToPeer.Collaboration.PeerChangeType
      description: The <xref href="System.Net.PeerToPeer.Collaboration.PeerChangeType"></xref> enumeration value that specifies the type of change that was performed on the <xref href="System.Net.PeerToPeer.Collaboration.PeerApplication"></xref>.
  overload: System.Net.PeerToPeer.Collaboration.ApplicationChangedEventArgs.PeerChangeType*
  exceptions: []
  platform:
  - net462
- uid: System.Net.PeerToPeer.Collaboration.ApplicationChangedEventArgs.PeerContact
  id: PeerContact
  parent: System.Net.PeerToPeer.Collaboration.ApplicationChangedEventArgs
  langs:
  - csharp
  name: PeerContact
  nameWithType: ApplicationChangedEventArgs.PeerContact
  fullName: System.Net.PeerToPeer.Collaboration.ApplicationChangedEventArgs.PeerContact
  type: Property
  assemblies:
  - System.Net
  namespace: System.Net.PeerToPeer.Collaboration
  summary: Gets the <xref href="System.Net.PeerToPeer.Collaboration.PeerContact"></xref> associated with the <xref href="System.Net.PeerToPeer.Collaboration.PeerApplication"></xref>.
  syntax:
    content: public System.Net.PeerToPeer.Collaboration.PeerContact PeerContact { get; }
    return:
      type: System.Net.PeerToPeer.Collaboration.PeerContact
      description: <xref href="System.Net.PeerToPeer.Collaboration.PeerContact"></xref> associated with the <xref href="System.Net.PeerToPeer.Collaboration.PeerApplication"></xref>.
  overload: System.Net.PeerToPeer.Collaboration.ApplicationChangedEventArgs.PeerContact*
  exceptions: []
  platform:
  - net462
- uid: System.Net.PeerToPeer.Collaboration.ApplicationChangedEventArgs.PeerEndPoint
  id: PeerEndPoint
  parent: System.Net.PeerToPeer.Collaboration.ApplicationChangedEventArgs
  langs:
  - csharp
  name: PeerEndPoint
  nameWithType: ApplicationChangedEventArgs.PeerEndPoint
  fullName: System.Net.PeerToPeer.Collaboration.ApplicationChangedEventArgs.PeerEndPoint
  type: Property
  assemblies:
  - System.Net
  namespace: System.Net.PeerToPeer.Collaboration
  summary: Gets the endpoint for which <xref href="System.Net.PeerToPeer.Collaboration.PeerApplication"></xref> information has changed.
  syntax:
    content: public System.Net.PeerToPeer.Collaboration.PeerEndPoint PeerEndPoint { get; }
    return:
      type: System.Net.PeerToPeer.Collaboration.PeerEndPoint
      description: The <xref href="System.Net.PeerToPeer.Collaboration.PeerEndPoint"></xref> that contains the endpoint for which application information has changed. Unless explicitly specified, the default value for all properties is <xref uid="langword_csharp_null" name="null" href=""></xref> for reference types and zero (0) for properties of type <xref uid="langword_csharp_int" name="int" href=""></xref>.
  overload: System.Net.PeerToPeer.Collaboration.ApplicationChangedEventArgs.PeerEndPoint*
  exceptions: []
  platform:
  - net462
references:
- uid: System.EventArgs
  isExternal: false
  name: System.EventArgs
- uid: System.Net.PeerToPeer.Collaboration.ApplicationChangedEventArgs.PeerApplication
  parent: System.Net.PeerToPeer.Collaboration.ApplicationChangedEventArgs
  isExternal: false
  name: PeerApplication
  nameWithType: ApplicationChangedEventArgs.PeerApplication
  fullName: System.Net.PeerToPeer.Collaboration.ApplicationChangedEventArgs.PeerApplication
- uid: System.Net.PeerToPeer.Collaboration.PeerApplication
  parent: System.Net.PeerToPeer.Collaboration
  isExternal: false
  name: PeerApplication
  nameWithType: PeerApplication
  fullName: System.Net.PeerToPeer.Collaboration.PeerApplication
- uid: System.Net.PeerToPeer.Collaboration.ApplicationChangedEventArgs.PeerChangeType
  parent: System.Net.PeerToPeer.Collaboration.ApplicationChangedEventArgs
  isExternal: false
  name: PeerChangeType
  nameWithType: ApplicationChangedEventArgs.PeerChangeType
  fullName: System.Net.PeerToPeer.Collaboration.ApplicationChangedEventArgs.PeerChangeType
- uid: System.Net.PeerToPeer.Collaboration.PeerChangeType
  parent: System.Net.PeerToPeer.Collaboration
  isExternal: false
  name: PeerChangeType
  nameWithType: PeerChangeType
  fullName: System.Net.PeerToPeer.Collaboration.PeerChangeType
- uid: System.Net.PeerToPeer.Collaboration.ApplicationChangedEventArgs.PeerContact
  parent: System.Net.PeerToPeer.Collaboration.ApplicationChangedEventArgs
  isExternal: false
  name: PeerContact
  nameWithType: ApplicationChangedEventArgs.PeerContact
  fullName: System.Net.PeerToPeer.Collaboration.ApplicationChangedEventArgs.PeerContact
- uid: System.Net.PeerToPeer.Collaboration.PeerContact
  parent: System.Net.PeerToPeer.Collaboration
  isExternal: false
  name: PeerContact
  nameWithType: PeerContact
  fullName: System.Net.PeerToPeer.Collaboration.PeerContact
- uid: System.Net.PeerToPeer.Collaboration.ApplicationChangedEventArgs.PeerEndPoint
  parent: System.Net.PeerToPeer.Collaboration.ApplicationChangedEventArgs
  isExternal: false
  name: PeerEndPoint
  nameWithType: ApplicationChangedEventArgs.PeerEndPoint
  fullName: System.Net.PeerToPeer.Collaboration.ApplicationChangedEventArgs.PeerEndPoint
- uid: System.Net.PeerToPeer.Collaboration.PeerEndPoint
  parent: System.Net.PeerToPeer.Collaboration
  isExternal: false
  name: PeerEndPoint
  nameWithType: PeerEndPoint
  fullName: System.Net.PeerToPeer.Collaboration.PeerEndPoint
- uid: System.Net.PeerToPeer.Collaboration.ApplicationChangedEventArgs.PeerApplication*
  parent: System.Net.PeerToPeer.Collaboration.ApplicationChangedEventArgs
  isExternal: false
  name: PeerApplication
  nameWithType: ApplicationChangedEventArgs.PeerApplication
- uid: System.Net.PeerToPeer.Collaboration.ApplicationChangedEventArgs.PeerChangeType*
  parent: System.Net.PeerToPeer.Collaboration.ApplicationChangedEventArgs
  isExternal: false
  name: PeerChangeType
  nameWithType: ApplicationChangedEventArgs.PeerChangeType
- uid: System.Net.PeerToPeer.Collaboration.ApplicationChangedEventArgs.PeerContact*
  parent: System.Net.PeerToPeer.Collaboration.ApplicationChangedEventArgs
  isExternal: false
  name: PeerContact
  nameWithType: ApplicationChangedEventArgs.PeerContact
- uid: System.Net.PeerToPeer.Collaboration.ApplicationChangedEventArgs.PeerEndPoint*
  parent: System.Net.PeerToPeer.Collaboration.ApplicationChangedEventArgs
  isExternal: false
  name: PeerEndPoint
  nameWithType: ApplicationChangedEventArgs.PeerEndPoint
